version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: crossword-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crossword-app
    depends_on:
      - db
    environment:
      # Flask/db.py возьмёт эту переменную
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
    ports:
      - "8080:5000"

volumes:
  db_data:
